function iframe1(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/c1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ch1_3.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe2(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe3(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar3.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar3.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar3.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar3.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe4(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe5(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ch1_3.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe6(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe7(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe8(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe9(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}
function iframe10(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar10.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar10.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar10.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar10.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe11(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe12(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe13(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}
function iframe14(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe15(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}

function iframe16(){
document.write("<script type=\"text\/javascript\">writeHTMLasJS1();<\/script><div class='ratio ratio-16x9'><iframe allowfullscreen='' frameborder='0' height='100%' id='iframe' mozallowfullscreen='' scrolling='no' sandbox=\"allow-same-origin allow-scripts\" src='https:\/\/www.footballontv.xyz\/p\/ar1.html' webkitallowfullscreen='' width='100%'><\/iframe><\/div><div class='servers-name' id='tabs'><a class='btn1 btn1-icon btn1-iframe' href=\"javascript:window.location.reload(true)\"><span>Refresh<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/www.footballontv.xyz\/p\/ar1.html\")'><span>CH 1<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 2<\/span><\/a><a class='btn1 btn1-icon btn1-iframe' onclick='dotab(this); setURL(\"https:\/\/tvinsurance.blogspot.com\/p\/ar1.html\")'><span>CH 3<\/span><\/a><\/div><script type=\"text\/javascript\">writeHTMLasJS2();<\/script>");
}
